version: '3.8'

services:

    mariadb:
        build: ./requirements/MariaDB
        image: mariadb:42
        container_name: mariadb
        env_file:
            - ./.env
        networks:
            - inception
        # healthcheck:
        #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
        restart: always

    # wordpress:
    #     build: ./requirements/WordPress
    #     image: wordpress:42
    #     container_name: wordpress
    #     env_file:
    #         - ./.env
    #     networks:
    #         - inception
    #     depends_on:
    #         - mariadb
    #     restart: always

    nginx:
        build: ./requirements/NGINX
        image: nginx:42
        container_name: nginx
        env_file:
            - ./.env
        networks:
            - inception
        ports:
            - "443:443"
        # depends_on:
        #     - wordpress
        restart: always

networks:
    inception:
        driver: bridge
        name: inception