version: '3.8'

services:

    mariadb:
        build: ./requirements/MariaDB
        image: mariadb:42
        container_name: mariadb
        env_file:
            - ./.env
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD"]
            interval: 10s
            timeout: 5s
            retries: 5
            # start_period: 5s
        restart: always

    wordpress:
        build: ./requirements/WordPress
        image: wordpress:42
        container_name: wordpress
        env_file:
            - ./.env
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        depends_on:
            - mariadb
        restart: always

    nginx:
        build: ./requirements/NGINX
        image: nginx:42
        container_name: nginx
        env_file:
            - ./.env
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress
        restart: always

volumes:
    mariadb:
    wordpress:

networks:
    inception:
        driver: bridge
        name: inception